<section>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6 col-lg-6 col-sm-12">
                        <a href="#">
                            <img src="image/internships.org.in.webp" alt="logo" height="70px" width="180px"
                                id="desktop-logo">
                        </a>
                    </div>
                    <div class="col-md-6 col-lg-6 col-sm-12 menu">
                        <a class="navbar-brand" href="#"></a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                            aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavDropdown">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Services</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Evants</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#">Contact us</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        Gallery
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Wedding Gallery </a></li>
                                        <li><a class="dropdown-item" href="#">Corporate Gallery</a></li>
                                        <li><a class="dropdown-item" href="#">Birthday Gallery</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <button class="btn btn-primary">Book Now</button>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

    </section>





     <section>
        <nav>

            <div class="logo">
                <img src="image/dreams logo.png" alt="">
                
            </div>

            <ul>
                <li><a href="">Home</a></li>
                <li><a href="">About</a></li>
                <li><a href="">Services</a></li>
                <li><a href="">Events</a></li>
                <li><a href="">Contact</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Gallery
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Wedding Gallery </a></li>
                        <li><a class="dropdown-item" href="#">Corporate Gallery</a></li>
                        <li><a class="dropdown-item" href="#">Birthday Gallery</a></li>
                    </ul>
                </li>
                <li>
                    <button class="btn btn-primary">Book Now</button>
                </li>
            </ul>

        </nav>
    </section>
